export const SIGN_IN = "SIGN_IN";
export const SIGN_UP = "SIGN_UP";
export const LOGOUT = "LOGOUT";

export const ADD_PROFILE = "ADD_PROFILE";

export const OPEN_SNACKBAR = "OPEN_SNACKBAR";
export const CLOSE_SNACKBAR = "CLOSE_SNACKBAR";

export const SET_PROFILE = "SET_PROFILE";
export const SET_PROFILE_AUTH = "SET_PROFILE_AUTH";
export const SET_PROFILE_NULL = "SET_PROFILE_NULL";
export const SET_ROLE = "SET_ROLE";
export const SET_PROFILE_ADDRESS = "SET_PROFILE_ADDRESS";
export const SET_ACCESS_RECAPTCHA = "SET_ACCESS_RECAPTCHA"
export const SET_AFFILIATOR = "SET_AFFILIATOR"
export const SET_TOKEN = "SET_TOKEN"
export const ADD_FRIEND_REQUEST = "ADD_FRIEND_REQUEST"
export const FILTER_FRIEND_REQUESTS = "FILTER_FRIEND_REQUESTS"

export const ADD_CARD = "ADD_CARD";
export const REMOVE_CARD = "REMOVE_CARD";
export const VALID_CARD = "VALID_CARD";

export const ADD_TO_CART = "ADD_TO_CART";
export const UPDATE_CART = "UPDATE_CART";
export const REMOVE_FROM_CART = "REMOVE_FROM_CART";
export const RESET_CART = "RESET_CART";
export const CHECKOUT = "CHECKOUT";
export const NEXT_STEP = "NEXT_STEP";
export const SET_DISCOUNT = "SET_DISCOUNT";
export const HAS_ERROR = "HAS_ERROR";
export const REMOVE_PRODUCT = "REMOVE_PRODUCT";
export const UPDATE_PRODUCT = "UPDATE_PRODUCT";
export const SET_STEP = "SET_STEP";
export const SET_DELIVERY = "SET_DELIVERY";
export const SET_NEXT_STEP = "SET_NEXT_STEP";
export const SET_BACK_STEP = "SET_BACK_STEP";
export const SET_BILLING_ADDRESS = "SET_BILLING_ADDRESS";
export const RESET_BILLING_ADDRESS = "RESET_BILLING_ADDRESS";
export const SET_SHIPPING_CHARGE = "SET_SHIPPING_CHARGE";
export const SET_PAYMENT_METHODE = "SET_PAYMENT_METHODE";
export const SET_PAYMENT_CART = "SET_PAYMENT_CART";
export const SET_PAYMENT_TYPE = "SET_PAYMENT_TYPE";
export const RESET_CARD = "RESET_CARD";
export const SET_COMPLETE = "SET_COMPLETE";
export const SET_SUBTOTAL = "SET_SUBTOTAL";
export const SET_TOTAL = "SET_TOTAL";
export const SET_CART_PRODUCTS = "SET_CART_PRODUCTS";
export const SET_TOTAL_QUANTITY = "SET_TOTAL_QUANTITY";
export const SET_TITLE_QUANTITY = "SET_TITLE_QUANTITY";
export const SET_OPEN = "SET_OPEN";
export const SET_EDIT = "SET_EDIT";
export const SET_DELIVERY_DATE = "SET_DELIVERY_DATE";

/**Enrollment */
export const SET_ENROLLMENTS = 'SET_ENROLLMENTS';
export const SET_CONVERSATION = 'SET_CONVERSATION';
export const ADD_TO_CONVERSATION = 'ADD_TO_CONVERSATION';
export const DELETE_CONVERSATION = 'DELETE_CONVERSATION';
export const ADD_ENROLLMENT_TO_CART = 'ADD_ENROLLMENT_TO_CART';
export const ADD_SELF_ENROLLMENT = 'ADD_SELF_ENROLLMENT';
export const UPDATE_ENROLLMENT_CART = 'UPDATE_ENROLLMENT_CART';
export const REMOVE_ENROLLMENT_FROM_CART = 'REMOVE_ENROLLMENT_FROM_CART';
export const SET_ENROLLMENT_DISCOUNT = 'SET_ENROLLMENT_DISCOUNT';
export const SET_CART_ENROLLMENTS = 'SET_CART_ENROLLMENTS';
export const SET_ENROLLMENT_BILLING_ADDRESS = 'SET_ENROLLMENT_BILLING_ADDRESS';
export const RESET_ENROLLMENT_BILLING_ADDRESS = 'RESET_ENROLLMENT_BILLING_ADDRESS';
export const SET_ENROLLMENT_PAYMENT_CARD = 'SET_ENROLLMENT_PAYMENT_CARD';
export const SET_ENROLLMENT_PAYMENT_METHODE = 'SET_ENROLLMENT_PAYMENT_METHODE';
export const SET_ENROLLMENT_OPEN_MENU = 'SET_ENROLLMENT_OPEN_MENU';
export const SET_ENROLLMENT_SUBTOTAL = 'SET_ENROLLMENT_SUBTOTAL';
export const SET_ENROLLMENT_TOTAL = 'SET_ENROLLMENT_TOTAL';
export const SET_ENROLLMENT_TOTAL_QUANTITY = 'SET_ENROLLMENT_TOTAL_QUANTITY';
export const RESET_ENROLLMENT_CARD = 'RESET_ENROLLMENT_CARD';
export const SET_ENROLLMENT_OPEN = 'SET_ENROLLMENT_OPEN';
export const SET_ENROLLMENT_STATUS = 'SET_ENROLLMENT_STATUS';
export const SET_ENROLLMENT_EDIT = 'SET_ENROLLMENT_EDIT';
export const SET_ENROLLMENT_START_DATE = 'SET_ENROLLMENT_START_DATE';
export const SET_ENROLLMENT_END_DATE = 'SET_ENROLLMENT_END_DATE'
export const SEARCH_PROFILE = 'SEARCH_PROFILE'

// Product
export const SET_PAGE_INDEX = "SET_PAGE_INDEX";
export const SET_SELF_PRODUCTS = "SET_SELF_PRODUCTS";
export const SET_PRODUCTS = "SET_PRODUCTS";
export const ADD_SELF_PRODUCT = "ADD_SELF_PRODUCT";
export const SET_PRODUCT = "SET_PRODUCT";
export const SET_ALL_PRODUCTS = "SET_ALL_PRODUCTS";
export const SET_PROMOTE = "SET_PROMOTE";
export const SET_PRODUCT_STATUS = "SET_PRODUCT_STATUS";
export const SET_SEARCH_RESULT = "SET_SEARCH_RESULT";

export const SET_SELECTION_STATUS = "SET_SELECTION_STATUS";
export const SET_SELECTIONS = "SET_SELECTIONS";
export const SET_SELF_SELECTIONS = "SET_SELF_SELECTIONS";
export const ADD_SELF_SELECTION = "ADD_SELF_SELECTION";
export const SET_SELECTION = "SET_SELECTION";
export const SET_SELECTED = "SET_SELECTED";
export const PROMOTE_SELECTION = "PROMOTE_SELECTION";

export const ADD_VIEWER = "ADD_VIEWER";
export const SET_VIEWER = "SET_VIEWER";
export const ADD_COLLABORATORS = "ADD_COLLABORATORS";
export const ADD_ORGANISATORS = "ADD_ORGANISATORS";
export const ADD_STUDS = "ADD_STUDS";
export const SET_COLLABORATORS = "SET_COLLABORATORS";
export const SET_ORGANISATORS = "SET_ORGANISATORS";
export const SET_CARD_BACK = "SET_CARD_BACK";
export const SET_MESSAGES = "SET_MESSAGES";


export const ADD_DISCOUNTS = "ADD_DISCOUNTS";

export const ADD_LIIS = "ADD_LIIS";
export const UPDATE_VIEWER_ADDRESS = "UPDATE_VIEWER_ADDRESS";
export const SET_VIEWER_AUTH = "SET_VIEWER_AUTH";
export const UPDATE_VIEWER = "UPDATE_VIEWER";
export const SET_VIEWER_NULL = "SET_VIEWER_NULL";
export const SET_COORDS = "SET_COORDS";
export const SET_ADDRESS_GEO = "SET_ADDRESS_GEO";
export const SET_FLAG_AVATAR = "SET_FLAG_AVATAR";
export const ADD_EVENT = "ADD_EVENT";
export const SET_ENROLLMENT_ALL = "SET_ENROLLMENT_ALL";
export const UPDATE_EVENT = "UPDATE_EVENT";
export const REMOVE_EVENT = "REMOVE_EVENT";
export const SET_EVENTS = "SET_EVENTS";
export const SET_SELECTED_EVENT = "SET_SELECTED_EVENT";
export const SET_SELECTED_DATE = "SET_SELECTED_DATE";



// Interface
export const SET_OPEN_MENU = "SET_OPEN_MENU";

// Tablet Organisator Cards

export const ADD_TABLET = "ADD_TABLET";
export const REMOVE_TABLET = "REMOVE_TABLET";
export const VALID_TABLET = "VALID_TABLET";
export const MOUNT_TABLETS = "MOUNT_TABLETS";
export const ACTIVATE = "ACTIVATE";
export const SET_SOURAS = "SET_SOURAS";
export const SET_SOURA = "SET_SOURA";
export const SET_SOURA_NAME = "SET_SOURA_NAME";
export const SET_SOURA_NMB = "SET_SOURA_NMB";
export const SET_TIWAL = "SET_TIWAL";
export const SET_MIIN = "SET_MIIN";
export const SET_MATHANI = "SET_MATHANI";
export const SET_MOFASAL = "SET_MOFASAL";
export const SET_TABLET = "SET_TABLET";
export const SET_CARDS = "SET_CARDS";
export const SET_CARDS_ACCORDION = "SET_CARDS_ACCORDION";
export const SET_AYAHS = "SET_AYAHS";
export const SET_SECTION = "SET_SECTION";
export const UPDATE_COLUMNS_ORDER = "UPDATE_COLUMNS_ORDER";
export const UPDATE_COLUMN_ITEM_ORDER = "UPDATE_COLUMN_ITEM_ORDER";
export const DELETE_ITEM = "DELETE_ITEM";
export const SET_NMB_TABLET = "SET_NMB_TABLET";
export const SET_TAB = "SET_TAB";
export const SET_WORDS = "SET_WORDS";
export const SET_TABLET_WORDS = "SET_TABLET_WORDS";
export const ADD_CARD_SLICES = "ADD_CARD_SLICES";
export const ADD_AYAT_CARDS = "ADD_AYAT_CARDS";
export const REMOVE_WORDS = "REMOVE_WORDS";
export const CLEAR_TABLET_WORDS = "CLEAR_TABLET_WORDS";
export const CLEAR_WORDS = "CLEAR_WORDS";
export const SET_OPEN_WORDS_DIALOG = "SET_OPEN_WORDS_DIALOG";
export const SET_OPEN_COMMENT_WORDS_DIALOG = "SET_OPEN_COMMENT_WORDS_DIALOG";
export const SET_WORD_AND_COMMENT = "SET_WORD_AND_COMMENT";
